### ISSUE TITLE
how to hot reload your config ? 

### ISSUE THREAD

**Issue by chenyangguang** [zouyx/agollo_demo#21]
How to reload your config cache  ?  GetConfigCache will always return cache config .

**Comment by zouyx** [comment]
> How to reload your config cache ? GetConfigCache will always return cache config .

不是太明白兄弟你的场景，cache 是用长轮询实时同步更新，除非。。。连不上远端，所以，在用户端不存在手工 reload 这种场景。

能具体描述一下你想达到什么效果吗？

**Comment by chenyangguang** [comment]
https://github.com/zouyx/agollo_demo/blob/master/custom/listener/check.go
 这个锁不太明白。
c2 := &CustomChangeListener{}
	c2.wg.Add(5)

	client,err:=agollo.StartWithConfig(func() (*config.AppConfig, error) {
		return c, nil
	})
	client.AddChangeListener(c2)


	fmt.Println("err:", err)

	c2.wg.Wait()

这个不是一直阻塞，知道调用  onChange 才起一个协程跑  push 的操作？那这个如果配置在启动阶段。就无限阻塞系统起来了。

**Comment by zouyx** [comment]
> https://github.com/zouyx/agollo_demo/blob/master/custom/listener/check.go
> 这个锁不太明白。
> c2 := &CustomChangeListener{}
> c2.wg.Add(5)
> 
> ```
> client,err:=agollo.StartWithConfig(func() (*config.AppConfig, error) {
> 	return c, nil
> })
> client.AddChangeListener(c2)
> 
> 
> fmt.Println("err:", err)
> 
> c2.wg.Wait()
> ```
> 
> 这个不是一直阻塞，知道调用 onChange 才起一个协程跑 push 的操作？那这个如果配置在启动阶段。就无限阻塞系统起来了。

这个wait group 是给你看效果的，让你看到你在http://106.54.227.205:8070 对应的 namespace 修改完之后会实时更新。

生产你不能用这个 wait group。

**Comment by chenyangguang** [comment]
> > https://github.com/zouyx/agollo_demo/blob/master/custom/listener/check.go
> > 这个锁不太明白。
> > c2 := &CustomChangeListener{}
> > c2.wg.Add(5)
> > ```
> > client,err:=agollo.StartWithConfig(func() (*config.AppConfig, error) {
> > 	return c, nil
> > })
> > client.AddChangeListener(c2)
> > 
> > 
> > fmt.Println("err:", err)
> > 
> > c2.wg.Wait()
> > ```
> > 
> > 
> > 这个不是一直阻塞，知道调用 onChange 才起一个协程跑 push 的操作？那这个如果配置在启动阶段。就无限阻塞系统起来了。
> 
> 这个wait group 是给你看效果的，让你看到你在http://106.54.227.205:8070 对应的 namespace 修改完之后会实时更新。
> 
> 生产你不能用这个 wait group。

生成的cache 之前的json 文件路径最好可配置。

**Comment by zouyx** [comment]
> > > https://github.com/zouyx/agollo_demo/blob/master/custom/listener/check.go
> > > 这个锁不太明白。
> > > c2 := &CustomChangeListener{}
> > > c2.wg.Add(5)
> > > ```
> > > client,err:=agollo.StartWithConfig(func() (*config.AppConfig, error) {
> > > 	return c, nil
> > > })
> > > client.AddChangeListener(c2)
> > > 
> > > 
> > > fmt.Println("err:", err)
> > > 
> > > c2.wg.Wait()
> > > ```
> > > 
> > > 
> > > 这个不是一直阻塞，知道调用 onChange 才起一个协程跑 push 的操作？那这个如果配置在启动阶段。就无限阻塞系统起来了。
> > 
> > 
> > 这个wait group 是给你看效果的，让你看到你在http://106.54.227.205:8070 对应的 namespace 修改完之后会实时更新。
> > 生产你不能用这个 wait group。
> 
> 生成的cache 之前的json 文件路径最好可配置。

你说的是备份的json 文件嘛？ 是这个属性 https://github.com/zouyx/agollo/blob/e35bcef3d07be7326e222fe8eab5b9a59c5697cd/env/config/config.go#L48

**Comment by chenyangguang** [comment]
那这个OnChange真实的使用方式是啥？如果不加锁，不加 sync.WaitGroup 的话，直接实例化一个CustomerListener ，会导致 OnChange 监听 push 事件 空指针。现在临时方案我只能想到，这个Sync.WaitGroup 的 wg.Add(10000) 加一个很大的数，表示 OnChange Apollo 变更没有那么频繁，耗不完 OnChange 监听。

**Comment by zouyx** [comment]
> 那这个OnChange真实的使用方式是啥？如果不加锁，不加 sync.WaitGroup 的话，直接实例化一个CustomerListener ，会导致 OnChange 监听 push 事件 空指针。现在临时方案我只能想到，这个Sync.WaitGroup 的 wg.Add(10000) 加一个很大的数，表示 OnChange Apollo 变更没有那么频繁，耗不完 OnChange 监听。

是否能提供一下实际代码？因为我认识的人都这么用，没有听说是 push 事件空指针。也不需要用 wg 等待。就是new 个对象 ，调用addchangelistener方法

**Comment by chenyangguang** [comment]
你不使用 wg, 直接 addchangelistenner 试一下，运行起来，会报错的。

**Comment by zouyx** [comment]
![截屏2020-12-13下午10 51 26](https://user-images.githubusercontent.com/3828072/102015303-bf124880-3d95-11eb-81e9-67e75cf190e0.png)

没有喔

**Comment by chenyangguang** [comment]
那是因为你仅仅触发了一次变更，第一次变更OnChange 调用时，wg.Done() 才消耗一个，等你的配置变更超过你设置的 wg.Add(n) 的时候，空指针的问题就出来了。

**Comment by zouyx** [comment]
> 那是因为你仅仅触发了一次变更，第一次变更OnChange 调用时，wg.Done() 才消耗一个，等你的配置变更超过你设置的 wg.Add(n) 的时候，空指针的问题就出来了。

你上一个回答让我不使用 wg，我就不使用 wg。那这一次你说要 wg，究竟是有没有 wg？

wg 只是在 demo 给你看效果的，实际生产上是不需要 wg。所以我不是太明白为什么生产上有 wg？

是否能提供具体代码，让我分析一下你的使用姿势是否正确？

**Comment by chenyangguang** [comment]
我是针对你的那个案例来说的。如果不设置waitGroup 那么，直接绑定 OnChangge 事件，那么就是一个 goroutine 子协程随时监听远程 appolo 更新事件了。 那就没问题的。

**Comment by zouyx** [comment]
> 我是针对你的那个案例来说的。如果不设置waitGroup 那么，直接绑定 OnChangge 事件，那么就是一个 goroutine 子协程随时监听远程 appolo 更新事件了。 那就没问题的。

是否能把你尝试出有问题的代码，发出来，我看看是否我的 demo 写的有问题？
